cmd /c mklink "C:\Users\$USERNAME\.tmux.conf" "C:\Users\git\dotfiles\tmux\.tmux.conf"
cmd /c mklink "C:\Users\$USERNAME\.tmux.conf.local" "C:\Users\git\dotfiles\tmux\.tmux.conf.local"
cmd /c mkdir "C:\Users\$USERNAME\.config"
cmd /c mklink "C:\Users\$USERNAME\.config\nvim" "C:\Users\git\dotfiles\nvim\"
cmd /c mklink "C:\Users\$USERNAME\.config\alacritty" "C:\Users\git\dotfiles\alacritty\"
cmd /c mklink "C:\Users\$USERNAME\.ideavimrc" "C:\Users\git\dotfiles\idea\.ideavimrc"
cmd /c mklink "C:\Users\$USERNAME\.config\fish\config.fish" "C:\Users\git\dotfiles\fish\config.fish"
cmd /c mklink "C:\Users\$USERNAME\.gitconfig" "C:\Users\git\dotfiles\git\.gitconfig"
cmd /c mklink "C:\Users\$USERNAME\.bashrc" "C:\Users\git\dotfiles\bash\.bashrc"